[package]
name = "oxidizy"
version = "0.1.0"
authors = ["selfup <boudinot.regis@yahoo.com>"]

[dependencies]
rustc-serialize = "0.3"
rayon = "0.3.1"
rand = "0.3"
iron = "*"
staticfile = "*"
router = "*"
mount = "*"
